version: '3'
services:
  app:
    image: app2-build
    ports:
    - "8080:8080"
    depends_on:
    - database

  database:
    image: mongo:latest
    ports:
    - "27017:27017"
    command: mongod
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
