mongo:
  database: database
  host: localhost
  port: 27017

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  data:
    web:
      pageable:
        default-page-size: 10
